# A generic, single database configuration.

[alembic]
# path to migration scripts
script_location = app/db/migrations

# template used to generate migration file names; The default value is %%(rev)s_%%(slug)s
# file_template = %%(year)d_%%(month).2d_%%(day).2d_%%(hour).2d_%%(minute).2d-%%(rev)s_%%(slug)s

# sys.path path, will be prepended to sys.path if present.
# defaults to the current working directory.
prepend_sys_path = .

# timezone to use when rendering the date within the migration file
# default to the timezone of the machine.
# timezone =

# max length of characters to apply to the "slug" field
# truncate_slug_length = 40

# set to 'true' to run the environment during
# the 'revision' command, regardless of autogenerate
# revision_environment = false

# set to 'true' to allow .pyc files to be created
# sourceless = false

# version location specification; This defaults
# to app/db/migrations/versions.  When using multiple version
# directories, separate them with spaces
# version_locations = %(here)s/bar/versions %(here)s/bat/versions

# the $ (dollar sign) is used to escape the % (percent sign)
# so that it is not interpreted as a variable.
sqlalchemy.url = postgresql://phantom:phantom@db:5432/phantom


[post_write_hooks]
# post_write_hooks allows scripts to be run after generating a migration file
# hooks are defined by name, then followed by configuration

# format using "black"
# hooks = black
# black.type = console_scripts
# black.entrypoint = black
# black.options = --line-length 79 REVISION_SCRIPT_FILENAME

# Logging configuration
[loggers]
keys = root,sqlalchemy,alembic

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = WARN
handlers = console
qualname =

[logger_sqlalchemy]
level = WARN
handlers =
qualname = sqlalchemy.engine

[logger_alembic]
level = INFO
handlers =
qualname = alembic

[handler_console]
class = StreamHandler
args = (sys.stdout,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s
datefmt = %H:%M:%S
